name: Print Commit Message

on:
  push:
    branches:
      - '*'

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print Commit Message
      run: echo "A commit was pushed to the repository!"
